name: Download Latest PAGASA Files
on:
  workflow_dispatch:  # Only manual trigger

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
          
      - name: Run download script
        run: |
          python codes/download_latest_pagasa.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Stage new files
        run: |
          git add codes/latest_*
          
      - name: Stash changes
        run: |
          git stash
          
      - name: Pull changes
        run: |
          git pull origin main --rebase
          
      - name: Apply stashed changes
        run: |
          git stash pop
          
      - name: Commit and push
        run: |
          git add codes/latest_*
          git commit -m "Update PAGASA files" || echo "No changes to commit"
          git push
