name: Update Wiki with Latest Pagasa Info
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 2,5,8,11,14,17,20,23 * **'
   
jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      
      - name: Get latest image/PDF from URL 1
        run: |
          python codes/get_latest_image_pdf.py -u "https://pubfiles.pagasa.dost.gov.ph/tamss/weather/bulletin/" -o codes/latest_tcb.txt
      
      - name: Get latest image/PDF from URL 2
        run: |
          python codes/get_latest_image_pdf.py -u "https://pubfiles.pagasa.dost.gov.ph/tamss/weather/weather_advisory/" -o codes/latest_wa.txt
      
      - name: Get latest image/PDF from URL 3
        run: |
          python codes/get_latest_image_pdf.py -u "https://pubfiles.pagasa.dost.gov.ph/climps/tcthreat/" -o codes/latest_tcthreat.txt
      
      - name: Update Wiki page
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            try {
              const tcb = fs.readFileSync('./codes/latest_tcb.txt', 'utf8');
              const wa = fs.readFileSync('./codes/latest_wa.txt', 'utf8');
              const tcthreat = fs.readFileSync('./codes/latest_tcthreat.txt', 'utf8');
              
              const content = `## Latest Pagasa Info\n\n**From URL 1:** ${tcb}\n**From URL 2:** ${wa}\n**From URL 3:** ${tcthreat}`;
              
              await github.rest.repos.updateWikiPage({
                owner: context.repo.owner,
                repo: context.repo.repo,
                page: 'Latest Pagasa Info',
                content: content,
                message: 'Update wiki content via GitHub Actions'
              });
            } catch (error) {
              console.error('Error:', error);
              core.setFailed(error.message);
            }
